#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

# border
bspc config border_width         1
bspc config window_gap          6

# misc
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colors
#wal -i ~/pictures/wallpapers/current
#. "~/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# picom
#picom --config ~/.config/picom/picom.config --experimental-backends
